#1. A blog - complete layout design, seo and support (till you learn to update it)
#2. Map explorer - All posts will be updated with pins(depends on how many posts you write). 
#3. Bitcoin/paypal integration to receive donation + ads integraion


baseurl: /
